server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          host: 127.0.01
          port: 8200
          kv-version: 2

management:
  endpoints:
    web:
      exposure:
        include: info, health, env

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
