server:
  port: 8888

spring:
  profiles:
    active: vault
  application:
    name: configservice

  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.01
          kv-version: 2
